core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('plantillas.urls')),
    path('plantillas/', include('plantillas.urls')),
    path('admin/', admin.site.urls),
]

plantillas/urls.py
from django.urls import path
from plantillas.views import saludo, inicio, some_view

from . import views

app_name = 'plantillas'

urlpatterns = [
    path('pdf', some_view),
    path('', inicio),

    path('<int:id>/', views.detail, name='detail'),

    path('<int:id>/results/', views.results, name='results'),

    path('<int:id>/vote/', views.vote, name='vote'),

    path('saludo/', saludo),
]

plantillas/models.py
from django.db import models

# Create your models here.


class Plantilla(models.Model):
    nombre = models.CharField(max_length=30)
    tipo = models.CharField(max_length=30)
    observaciones = models.TextField()

    def __str__(self):
        return self.nombre

plantillas/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect, FileResponse
# from django.template import loader
from django.urls import reverse

from .models import Plantilla
import datetime

import io
from reportlab.pdfgen import canvas

# Create your views here.


def some_view(request):
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()

    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)

    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, "Hello world.")
    p.drawString(0, 400, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ullamcorper urna et erat aliquet sollicitudin. Morbi faucibus nibh sodales, convallis ante eget, venenatis ex. Vivamus interdum ultricies dapibus. Nam tempus, turpis a porta aliquet, est ex pulvinar diam, sit amet convallis turpis ex a metus. Praesent tincidunt hendrerit pellentesque. Pellentesque quis feugiat odio, a varius augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc pharetra, enim vel interdum pharetra, magna nunc malesuada dui, vitae tincidunt est diam a odio. Nulla vitae maximus mi. Nunc eget felis tortor. Nulla rhoncus rutrum felis, a placerat magna lacinia at. Curabitur eget urna metus. In accumsan ipsum in diam aliquet euismod. Vivamus ante nunc, pharetra et. ")

    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()

    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='hello.pdf')


def saludo(request):
    fecha = datetime.datetime.now().year
    texto = '<h3>Hola estamos a %s </h3>' % fecha
    return HttpResponse(texto)


def inicio(request):
    context = {

    }
    return render(request, 'plantillas/base.html', context)


def index(request):
    latest_question_list = Plantilla.objects.order_by('-nombre')[:5]
    # template = loader.get_template('plantillas/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'plantillas/index.html', context)


def detail(request, id):
    question = get_object_or_404(Plantilla, pk=id)
    return render(request, 'plantillas/detail.html', {'question': question})

    # return HttpResponse("Estas  viendo el detalle de una plantilla determinada %s. " % id)


def results(request, id):
    response = "Estas buscando resultados para la palabra %s. "
    question = get_object_or_404(Plantilla, pk=id)
    return render(request, 'plantillas/results.html', {'question': question})
    # return HttpResponse(response % id)


def vote(request, id):
    question = get_object_or_404(Plantilla, pk=id)
    try:
        selected_choice = question
    except (KeyError, Plantilla.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'plantillas/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.tipo = request.POST['tipo']
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('plantillas:results', args=(question.id,)))

        # return HttpResponse("Esto es otra cosa %s." % id)

plantillas/templates/plantillas/aside.html
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h1 class="accordion-header" id="headingOne">
        <button class="accordion-button text-primary p-1" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <h5 class="menu2" style="font-weight: 500;font-size: 18px;"><strong>Clientes</strong></h5>
        </button>
      </h1>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
        data-bs-parent="#accordionExample">
        <div class="accordion-body pt-0">
          <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Nombre/Cif/Nif:</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
            <button type="submit" class="btn btn-primary btn-sm">Reset</button>
          </form>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button text-primary p-1" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <h5>Nif</h5>
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse show" aria-labelledby="headingTwo"
        data-bs-parent="#accordionExample">
        <div class="accordion-body pt-0">
          <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Nif:</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
            <button type="submit" class="btn btn-primary btn-sm">Reset</button>
          </form>
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed text-primary p-1" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <h5>Escaner</h5>
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
        data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <form>
            <div class="mb-3">
              <label for="exampleInputEmail1" class="form-label">Nombre/Cif/Nif:</label>
              <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
              <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1">
            </div>
            <div class="mb-3 form-check">
              <input type="checkbox" class="form-check-input" id="exampleCheck1">
              <label class="form-check-label" for="exampleCheck1">Check me out</label>
            </div>
            <button type="submit" class="btn btn-primary btn-sm">Buscar</button>
            <button type="submit" class="btn btn-primary btn-sm">Reset</button>
          </form>
        </div>
      </div>
    </div>
  </div>

plantillas/templates/plantillas/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'plantillas/css/reboot.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'plantillas/css/estilos.css' %}">
    <title>Grupo Asesor Ros</title>
</head>
    <body class="bg-white">
        <!-- NAVBAR 1 -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" aria-label="Fifth navbar example">
        <div class="container-fluid">
            <a class="navbar-brand align-top me-auto" href="#">Grupo Asesor Ros</a>
            <ul class="navbar-nav mb-0 mb-sm-0">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Web</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Ayuda</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled">F.Martínez</a>
            </li>
            </ul>
        </div>
        </nav>
        <!-- End of NAVBAR 1 -->
        <!-- NAVBAR 2 -->
        <div class="container-fluid sticky-top bg-white mb-0" style="border-bottom: 1px solid #cccccc;">
            <header class="d-flex flex-wrap justify-content-center py-2  align-items-center">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <img src="{% static 'plantillas/images/logo.png' %}" class="rounded float-start" alt="Grupo Asesor Ros">
            </a>
            <ul class="nav nav-pills menu">
                <li class="nav-item"><a href="#" class="nav-link fw-bolder" aria-current="page">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link fw-bolder">Documentos</a></li>
                <li class="nav-item"><a href="#" class="nav-link fw-bolder">Notificaciones</a></li>
                <li class="nav-item"><a href="#" class="nav-link fw-bolder">Horarios</a></li>
                <li class="nav-item"><a href="#" class="nav-link fw-bolder">Administracion</a></li>
            </ul>
            </header>
        </div>

        <!-- MAIN CONTENT -->
        <div class="d-flex container-fluid m-0 px-1">
            <!-- ASIDE -->
            <aside style="padding: 12px;width:310px;border-right: 1px solid #cccccc !important;">
                {% include "plantillas/aside.html" %}
            </aside>
            <!-- End of ASIDE -->

            <!-- SECTION -->
            <section class="flex-fill" style="padding: 12px">
                <article>
               
                </article>
            </section>
            <!-- End of SECTION -->
        </div>
        <!-- End of MAIN CONTENT -->
        <script src="{% static 'plantillas/js/bootstrap.min.js' %}"></script>
    </body>
</html>

plantillas/templates/plantillas/detail.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Titulo Documento</title>
    </head>
    <body>
        <form action="{% url 'plantillas:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{ question.nombre }}</h1></legend>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
                
                    <input type="input" name="tipo" id="tipo" value="{{ question.tipo }}">
                    <label for="tipo">Tipo: </label><br>
                
            </fieldset>
            <input type="submit" value="Vote">
        </form>
    </body>
</html>

plantillas/templates/plantillas/index.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>Titulo Documento</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plantillas/style.css' %}">  
    </head>
    <body>
        <p>Hola que tal estas</p>
        <p>oops</p>
        {% if latest_question_list %}
        <ul>
        {% for plantillas in latest_question_list %}
            <li><a href="{% url 'plantillas:detail' plantillas.id %}">{{ plantillas.nombre }}</a></li>
        {% endfor %}
        </ul>
        {% else %}
            <p>No polls are available.</p>
        {% endif %}
    </body>
</html>

plantillas/templates/plantillas/results.html
<h1>{{ question.nombre }}</h1>

<ul>

    <li>- {{ question.tipo }}</li>

</ul>

<a href="{% url 'plantillas:detail' question.id %}">Volver a modificar</a>